version: '3.3'

services:
  web:
    container_name: laravel
    image: jjuanrivvera99/ubuntu-apache-php-postgresql:alegra
    build:
      context: ./docker/laravel
    ports:
      - 80:80
    volumes:
      - ./core:/var/www

  redis:
    container_name: redis
    image: redis
    build:
      context: ./docker/redis
    restart: always

  pgsql:
    container_name: postgres
    image: postgres
    build:
      context: ./docker/pgsql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "juan.rivera@alegra.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - 8080:80

volumes:
  pgdata: