version: '3.3'

services:
  web:
    container_name: laravel
    image:  registry.heroku.com/alegra-test/web
    restart: always
    depends_on:
      - redis
    build:
      context: ./docker/laravel
    ports:
      - 80:80
    volumes:
      - ./core:/var/www

  queue:
    container_name: queue
    restart: always
    depends_on:
      - redis
    image:  registry.heroku.com/alegra-test/web
    environment:
      CONTAINER_ROLE: "queue"
    volumes:
      - "./core:/var/www/"

  scheduler:
    container_name: scheduler
    restart: always
    depends_on:
      - redis
    image: registry.heroku.com/alegra-test/web
    environment:
      CONTAINER_ROLE: "scheduler"
    volumes:
      - "./core:/var/www/"

  socket-io:
    container_name: socket-io
    restart: always
    depends_on:
      - redis
    image: registry.heroku.com/alegra-test/web
    ports:
      - 8081:8081
    environment:
      CONTAINER_ROLE: "socket.io"
    volumes:
      - "./core:/var/www/"

  redis:
    container_name: redis
    image: registry.heroku.com/alegra-test/redis
    build:
      context: ./docker/redis
    restart: always

  pgsql:
    container_name: postgres
    image: registry.heroku.com/alegra-test/postgres
    build:
      context: ./docker/pgsql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "juan.rivera@alegra.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80

volumes:
  pgdata:
  pgadmin: